  domain: forgeops.com
  service:
    name: idm-service
    externalPort: 8080
    type: NodePort
  resources:
    requests:
      memory: "512Mi"
  config:
    strategy: files
    path: /opt/openidm
  openidm:
    repo:
      host: configstore-0.configstore
      port: 1389
      user: "cn=Directory Manager"
      password: password
